apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lrcs.fullname" . }}-backend
  labels:
    app: {{ include "lrcs.name" . }}-backend
    tier: {{ include "lrcs.name" . }}-backend
    environment: {{ .Values.environment }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "lrcs.name" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "lrcs.name" . }}-backend
        tier: {{ include "lrcs.name" . }}-backend
        environment: {{ .Values.environment }}
    spec:
      restartPolicy: {{ .Values.restartPolicy }}
      containers:
      - name: {{ include "lrcs.name" . }}-backend
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ required "containerPort is required!" .Values.containerPort | int }}
        envFrom:
        - secretRef:
            name: {{ .Values.secretRefName }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 12 }}
        {{- end }}