apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: mongodb
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=  # base64 for "admin"
  MONGO_INITDB_ROOT_PASSWORD: c2VjcmV0  # base64 for "secret"