# The environment (e.g., production, staging, development)
environment: production
nameOverride: "lrcs"
fullnameOverride: "lrcs"

# Docker image settings
image:
  repository: docjas143/lrcs-backend
  tag: latest # Change to a specific version/tag in production!
  pullPolicy: Always

# Number of backend pods to run
replicaCount: 2

# Pod container settings
containerPort: 3001
restartPolicy: Always

# Kubernetes Service for the backend
service: 
  type: LoadBalancer
  port: 3001
  targetPort: 3001
      
# Kubernetes Secret Reference (if you store secrets in K8s)
secretRefName: backend-secrets

  # Direct secrets (prefer using sealed-secrets or external secrets in production)
secret:
  atlasuri: bW9uZ29kYjovL2FkbWluOnNlY3JldEBtb25nby5tb25nb2RiLnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3L2xyY3M/YXV0aFNvdXJjZT1hZG1pbg==
  jwtsecretkey: dGhpc2lzd3RzZWNyZXRrZXQ=
  port: MzAwMQ==

# Liveness probe for backend health
livenessProbe:
  httpGet:
    path: /health
    port: 3001
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 2

# Readiness probe for backend readiness
readinessProbe:
  httpGet:
    path: /health
    port: 3001
  initialDelaySeconds: 40
  periodSeconds: 5
  failureThreshold: 3
  timeoutSeconds: 2

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"